name: healmeumpapp
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  dio: ^5.7.0
  bloc: ^8.1.4
  shared_preferences: ^2.3.4
  shimmer: ^3.0.0
  get_it: ^8.0.3
  dartz: ^0.10.1
  connectivity_plus: ^6.1.1
  flutter_bloc: ^8.1.6
  go_router: ^14.6.2
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  flutter_flavor: ^3.1.4
  sizer: ^3.0.5
  fluttertoast: ^8.2.10
  geocoding: ^3.0.0
  chucker_flutter: ^1.8.3
  intl: ^0.19.0
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.14.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
